.. vim:ft=rst

.. Course
.. _mailing list: https://calmail.berkeley.edu/manage/list/listinfo/practical_fmri@lists.berkeley.edu
.. _course web directory: http://nipy.bic.berkeley.edu/practical_neuroimaging/

.. BIC
.. _BIC:
.. _Brain Imaging Center:
.. _Berkeley Brain Imaging Center: http://bic.berkeley.edu
.. _practiCAL fMRI blog: https://practicalfmri.blogspot.com
.. _practical neuroimaging course: http://practical-neuroimaging.github.io
.. _neuro cluster: https://www.neuro.berkeley.edu

.. Python distributions
.. _homebrew: http://brew.sh

.. Version control
.. _git: http://git-scm.com
.. _git OSX installer: http://mackyle.github.io/git-osx-installer/
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com

.. Editors
.. _vim: http://www.vim.org
.. _vi: http://en.wikipedia.org/wiki/Vi
.. _about vim: http://www.vim.org/about.php
.. _emacs tour: http://www.gnu.org/software/emacs/tour/
.. _vim: http://www.vim.org
.. _gvim: http://www.vim.org
.. _textmate: http://macromates.com
.. _textmate download for UC Berkeley: http://ist.berkeley.edu/software-central/textmate
.. _text wrangler: http://www.barebones.com/products/textwrangler/
.. _sublime text: http://www.sublimetext.com/
.. _gedit: http://projects.gnome.org/gedit
.. _emacs: http://www.gnu.org/software/emacs/
.. _text editor competition:
   http://www.rackspace.com/blog/text-editor-madness-bracket-vote-for-your-favorite
.. _atom: https://atom.io
.. _hydrogen: https://atom.io/packages/hydrogen
.. _installing atom: http://flight-manual.atom.io/getting-started/sections/installing-atom
.. _atom releases: https://github.com/atom/atom/releases
.. _vim-mode: https://github.com/atom/vim-mode
.. _ex-mode: https://atom.io/packages/ex-mode
.. _emacs-mode: https://atom.io/packages/emacs-mode
.. _notepad++: https://notepad-plus-plus.org
.. _pycharm: http://www.jetbrains.com/pycharm

.. Python and common libraries
.. _python: https://www.python.org
.. _python standard library: http://docs.python.org/3/library
.. _python.org releases: http://www.python.org/download/releases
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _numpy: http://www.numpy.org
.. _scipy: http://www.scipy.org
.. _scipy reference guide: http://docs.scipy.org/doc/scipy/reference/
.. _matplotlib: http://matplotlib.org/
.. _matplotlib gallery: http://matplotlib.org/gallery
.. _cython: http://cython.org/
.. _sympy: http://sympy.org
.. _pandas: http://pandas.pydata.org/
.. _scikit-learn: http://scikit-learn.org/
.. _scikit-image: http://scikit-image.org/
.. _statsmodels: http://www.statsmodels.org/
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _pip: http://pypi.python.org/pypi/pip
.. _sphinx: http://www.sphinx-doc.org
.. _10 reasons Python rocks for research:
   http://www.stat.washington.edu/~hoytak/blog/whypython.html
.. _install pip with get-pip.py: https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py

.. IPython
.. _ipython: http://ipython.org/
.. _ipython notebook: http://ipython.org/ipython-doc/dev/interactive/htmlnotebook.html

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _macports: http://www.macports.org
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: https://github.com/b4winckler/macvim
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com

.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Nipy and friends
.. _nipy community: http://nipy.org
.. _nipy project: http://nipy.org/nipy
.. _nibabel: http://nipy.org/nibabel
.. _dipy: http://nipy.org/dipy
.. _nipype: http://nipy.org/nipype
.. _gitwash: http://github.com/matthew-brett/gitwash

.. FMRI datasets
.. _openfmri: https://openfmri.org/
.. _duncan et al data: https://openfmri.org/dataset/ds000107
.. _ds107 dataset: https://openfmri.org/dataset/ds000107
.. _ds114 dataset: https://openfmri.org/dataset/ds000114

.. Languages
.. _matlab: http://www.mathworks.com

.. Imaging software
.. _spm: http://www.fil.ion.ucl.ac.uk/spm
.. _eeglab: http://sccn.ucsd.edu/eeglab
.. _AFNI: http://afni.nimh.nih.gov/afni
.. _FSL: http://www.fmrib.ox.ac.uk/fsl
.. _FreeSurfer: http://surfer.nmr.mgh.harvard.edu
.. _voxbo: http://www.voxbo.org
.. _fmristat: http://www.math.mcgill.ca/keith/fmristat

.. Installation
.. _Python(X,Y): https://python-xy.github.io
.. _Python(X,Y) UK mirror: http://www.mirrorservice.org/sites/pythonxy.com
.. _blocked by Google code: http://nipyworld.blogspot.com/2011/07/why-you-shouldnt-use-google-code.html
.. _Enthought Python Distribution: http://www.enthought.com/products/epd.php
.. _Anaconda: https://www.continuum.io/why-anaconda
.. _EPD: http://www.enthought.com/products/epd.php
.. _Enthought canopy: https://www.enthought.com/products/canopy/
.. _checklist script: http://fperez.org/py4science/workshop_checklist.py
.. _NeuroDebian: http://neuro.debian.net
.. _VirtualBox: https://www.virtualbox.org/

.. Tutorials
.. _The Python tutorial: http://docs.python.org/2/tutorial/
.. _The Python 3 tutorial: http://docs.python.org/3/tutorial/
.. _Introduction to Python: http://www.introtopython.org
.. _Scipy lecture notes: http://scipy-lectures.github.io
.. _numpy introduction: http://scipy-lectures.github.io/intro/numpy/index.html
.. _numpy array object: http://scipy-lectures.github.io/intro/numpy/array_object.html
.. _Array operations: http://scipy-lectures.github.io/intro/numpy/operations.html
.. _Google Python class: https://developers.google.com/edu/python
.. _basic exercises: https://developers.google.com/edu/python/exercises/basic

.. MB tutorials
.. _curious git: https://matthew-brett.github.io/curious-git/index.html
.. _introduction to Principal Components Analysis:
.. _pca introduction: https://matthew-brett.github.io/teaching/pca_introduction.html
.. _introduction to the General Linear Model:
.. _GLM intro: https://matthew-brett.github.io/teaching/glm_intro.html
.. _tutorial on convolution:
   https://matthew-brett.github.io/teaching/on_convolution.html
.. _tutorial on correlated regressors:
   https://matthew-brett.github.io/teaching/correlated_regressors.html
.. _Bonferroni correction:
   https://matthew-brett.github.io/teaching/bonferroni_correction.html
.. _FDR:
.. _False Discovery Rate:
   https://matthew-brett.github.io/teaching/fdr.html
.. _random fields:
   https://matthew-brett.github.io/teaching/random_fields.html
.. _slice timing correction:
   https://matthew-brett.github.io/teaching/slice_timing.html
.. _optimizing space:
.. _optimizing spatial transformations:
   https://matthew-brett.github.io/teaching/optimizing_space.html
.. _mutual information:
   https://matthew-brett.github.io/teaching/mutual_information.html
.. _Coordinate systems and affine transforms:
   http://nipy.org/nibabel/coordinate_systems.html
.. _floating point:
   https://matthew-brett.github.io/teaching/floating_point.html
.. _floating point error:
   https://matthew-brett.github.io/teaching/floating_error.html
.. _introduction to smoothing:
   https://matthew-brett.github.io/teaching/smoothing_intro.html
.. _smoothing as convolution:
   https://matthew-brett.github.io/teaching/smoothing_as_convolution.html
.. _rotation in 2D:
   https://matthew-brett.github.io/teaching/rotation_2d.html

.. Ideas
.. _principal component analysis:
   https://en.wikipedia.org/wiki/Principal_component_analysis
.. _linear interpolation:
    http://en.wikipedia.org/wiki/Linear_interpolation
.. _nearest neighbor interpolation:
    https://en.wikipedia.org/wiki/Nearest-neighbor_interpolation

.. People
.. _Matthew:
.. _Matthew Brett : http://matthew.dynevor.org
.. _Richard Stallman: http://en.wikipedia.org/wiki/Richard_Stallman

.. Licenses
.. _cc-by-nc-sa: http://creativecommons.org/licenses/by-nc-sa/4.0
.. _pddl 1.0: http://opendatacommons.org/licenses/pddl/1.0/

.. Neuroimaging stuff
.. _BOLD: https://en.wikipedia.org/wiki/Blood-oxygen-level_dependent
.. _blood-oxygen-level dependent: https://en.wikipedia.org/wiki/Blood-oxygen-level_dependent
.. _convolution: https://en.wikipedia.org/wiki/Convolution
.. _impulse response: https://en.wikipedia.org/wiki/Impulse_response
.. _boxcar function: https://en.wikipedia.org/wiki/Boxcar_function

.. OpenFMRI projects
.. _ds005: https://openfmri.org/dataset/ds000005
.. _ds009: https://openfmri.org/dataset/ds000009
.. _ds105: https://openfmri.org/dataset/ds000105
.. _ds113: https://openfmri.org/dataset/ds000113
.. _ds115: https://openfmri.org/dataset/ds000115

.. Unix
.. _PATH: http://www.jarrodmillman.com/rcsds/standard/bash.html#commands

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
