coordinate_grid[:, 0, 0]  # look up new coordinate for (0, 0)
# array([2, 0])
coordinate_grid[:, 1, 0]  # look up new coordinate for (1, 0)
# array([3, 0])
coordinate_grid[:, 0, 1]  # look up new coordinate for (0, 1)
# array([2, 1])
